// Code generated by a template
using System;
using System.ComponentModel.DataAnnotations;

namespace EF.T4.Mssql
{
    public partial class GZ_AttendanceDetail
    {
        /// <summary>
        ///
        /// </summary>
        [Key]
        public Guid Id {set;get;}
        /// <summary>
        ///
        /// </summary>
        public Guid AttendanceId {set;get;}
        /// <summary>
        ///
        /// </summary>
        public DateTime TimeDay {set;get;}
        /// <summary>
        ///
        /// </summary>
        public Decimal SickLeave {set;get;}
        /// <summary>
        ///
        /// </summary>
        public Decimal CompassionateLeave {set;get;}
        /// <summary>
        ///
        /// </summary>
        public Decimal BreakDown {set;get;}
        /// <summary>
        ///
        /// </summary>
        public Decimal AnnualLeave {set;get;}
        /// <summary>
        ///
        /// </summary>
        public Decimal OtherLeave {set;get;}
        /// <summary>
        ///
        /// </summary>
        public Decimal Belate {set;get;}
        /// <summary>
        ///
        /// </summary>
        public Decimal LeaveEarly {set;get;}
        /// <summary>
        ///
        /// </summary>
        public Nullable<Guid> CreateUser {set;get;}
        /// <summary>
        ///
        /// </summary>
        public Nullable<DateTime> CreateDate {set;get;}
    }

}
// It's the end
