// Code generated by a template
using System;
using System.ComponentModel.DataAnnotations;

namespace EF.T4.Mssql
{
    public partial class GZ_Attachment
    {
        /// <summary>
        ///
        /// </summary>
        [Key]
        public Guid Id {set;get;}
        /// <summary>
        ///
        /// </summary>
        public Guid SourceId {set;get;}
        /// <summary>
        ///
        /// </summary>
        public Int32 Category {set;get;}
        /// <summary>
        ///
        /// </summary>
        [Required]
        [StringLength(512)]
        public String FilePath {set;get;}
    }

}
// It's the end
