// Code generated by a template
using System;
using System.ComponentModel.DataAnnotations;

namespace EF.T4.Mssql
{
    public partial class GZ_HouseMoneyDetail
    {
        /// <summary>
        ///
        /// </summary>
        [Key]
        public Guid Id {set;get;}
        /// <summary>
        ///
        /// </summary>
        [Required]
        [StringLength(50)]
        public String Account {set;get;}
        /// <summary>
        ///
        /// </summary>
        [Required]
        [StringLength(50)]
        public String Name {set;get;}
        /// <summary>
        ///
        /// </summary>
        [Required]
        [StringLength(50)]
        public String IDCard {set;get;}
        /// <summary>
        ///
        /// </summary>
        public Decimal PaymentStandard {set;get;}
        /// <summary>
        ///
        /// </summary>
        public Decimal CorpRate {set;get;}
        /// <summary>
        ///
        /// </summary>
        public Decimal PersonalRate {set;get;}
        /// <summary>
        ///
        /// </summary>
        [Required]
        [StringLength(200)]
        public String Total_Pwd {set;get;}
        /// <summary>
        ///
        /// </summary>
        public Guid SubjectId {set;get;}
        /// <summary>
        ///
        /// </summary>
        [Required]
        [StringLength(200)]
        public String CorpMoney_Pwd {set;get;}
        /// <summary>
        ///
        /// </summary>
        [Required]
        [StringLength(200)]
        public String PersonalMoney_Pwd {set;get;}
    }

}
// It's the end
