// Code generated by a template
using System;
using System.ComponentModel.DataAnnotations;

namespace EF.T4.Mssql.ZS
{
    public partial class GZ_Attendance
    {
        /// <summary>
        ///
        /// </summary>
        [Key]
        public Guid Id {set;get;}
        /// <summary>
        ///
        /// </summary>
        public Guid CompanyId {set;get;}
        /// <summary>
        ///
        /// </summary>
        public Guid DepartmentId {set;get;}
        /// <summary>
        ///
        /// </summary>
        public Guid EmployeeId {set;get;}
        /// <summary>
        ///
        /// </summary>
        public Int32 KProjectId {set;get;}
        /// <summary>
        ///
        /// </summary>
        [Required]
        [StringLength(50)]
        public String Name {set;get;}
        /// <summary>
        ///
        /// </summary>
        [Required]
        [StringLength(20)]
        public String Mobile {set;get;}
        /// <summary>
        ///
        /// </summary>
        [Required]
        [StringLength(7)]
        public String Month {set;get;}
        /// <summary>
        ///
        /// </summary>
        public Decimal TotalDays {set;get;}
        /// <summary>
        ///
        /// </summary>
        public Decimal RealDays {set;get;}
        /// <summary>
        ///
        /// </summary>
        public Decimal AbsenteeismDays {set;get;}
        /// <summary>
        ///
        /// </summary>
        public Decimal SickLeave {set;get;}
        /// <summary>
        ///
        /// </summary>
        public Decimal CompassionateLeave {set;get;}
        /// <summary>
        ///
        /// </summary>
        public Decimal BreakDown {set;get;}
        /// <summary>
        ///
        /// </summary>
        public Decimal AnnualLeave {set;get;}
        /// <summary>
        ///
        /// </summary>
        public Decimal OtherLeave {set;get;}
        /// <summary>
        ///
        /// </summary>
        public Decimal LeaveMinute {set;get;}
        /// <summary>
        ///
        /// </summary>
        public Decimal BelateByHour {set;get;}
        /// <summary>
        ///
        /// </summary>
        public Decimal BelateMinute {set;get;}
        /// <summary>
        ///
        /// </summary>
        public Decimal OutsideMinute {set;get;}
        /// <summary>
        ///
        /// </summary>
        public Decimal LeaveEarlyMinute {set;get;}
        /// <summary>
        ///
        /// </summary>
        [StringLength(1024)]
        public String Remark {set;get;}
        /// <summary>
        ///
        /// </summary>
        public Int32 Status {set;get;}
        /// <summary>
        ///
        /// </summary>
        public Decimal FinalDays {set;get;}
        /// <summary>
        ///
        /// </summary>
        public Int32 DataSourceType {set;get;}
        /// <summary>
        ///
        /// </summary>
        public Nullable<Guid> LastUpdateUser {set;get;}
        /// <summary>
        ///
        /// </summary>
        public Nullable<DateTime> LastUpdateDate {set;get;}
        /// <summary>
        ///
        /// </summary>
        public Nullable<Guid> CreateUser {set;get;}
        /// <summary>
        ///
        /// </summary>
        public Nullable<DateTime> CreateDate {set;get;}
    }

}
// It's the end
