// Code generated by a template
using System;
using System.ComponentModel.DataAnnotations;

namespace EF.T4.Mssql.ZS
{
    public partial class GZ_ApproveLog
    {
        /// <summary>
        ///
        /// </summary>
        [Key]
        public Guid Id {set;get;}
        /// <summary>
        ///
        /// </summary>
        public Guid TargetId {set;get;}
        /// <summary>
        ///
        /// </summary>
        public Guid OperatorId {set;get;}
        /// <summary>
        ///
        /// </summary>
        public DateTime OperatorTime {set;get;}
        /// <summary>
        ///
        /// </summary>
        public Int32 Category {set;get;}
        /// <summary>
        ///
        /// </summary>
        [Required]
        [StringLength(1024)]
        public String Comment {set;get;}
        /// <summary>
        ///
        /// </summary>
        [Required]
        [StringLength(50)]
        public String TargetTable {set;get;}
        /// <summary>
        ///
        /// </summary>
        public Int32 TargetStatus {set;get;}
    }

}
// It's the end
