// Code generated by a template
using System;
using System.ComponentModel.DataAnnotations;

namespace EF.T4.Mssql.ZS
{
    public partial class GZ_Department
    {
        /// <summary>
        ///
        /// </summary>
        [Key]
        public Guid Id {set;get;}
        /// <summary>
        ///
        /// </summary>
        [Required]
        [StringLength(500)]
        public String Name {set;get;}
        /// <summary>
        ///
        /// </summary>
        public Guid CpId {set;get;}
        /// <summary>
        ///
        /// </summary>
        public Int32 UcDepartmentId {set;get;}
        /// <summary>
        ///
        /// </summary>
        public Int32 Status {set;get;}
        /// <summary>
        ///
        /// </summary>
        public Int32 Order {set;get;}
    }

}
// It's the end
