// Code generated by a template
using System;
using System.ComponentModel.DataAnnotations;

namespace EF.T4.Mssql.ZS
{
    public partial class GZ_Employee
    {
        /// <summary>
        ///
        /// </summary>
        [Key]
        public Guid Id {set;get;}
        /// <summary>
        ///
        /// </summary>
        [Required]
        [StringLength(50)]
        public String Name {set;get;}
        /// <summary>
        ///
        /// </summary>
        public Guid CorpId {set;get;}
        /// <summary>
        ///
        /// </summary>
        public Guid DepartmentId {set;get;}
        /// <summary>
        ///
        /// </summary>
        public Nullable<Guid> FinacialUnitId {set;get;}
        /// <summary>
        ///
        /// </summary>
        [Required]
        [StringLength(50)]
        public String Mobile {set;get;}
        /// <summary>
        ///
        /// </summary>
        [StringLength(50)]
        public String IDCard {set;get;}
        /// <summary>
        ///
        /// </summary>
        [StringLength(50)]
        public String BankCard {set;get;}
        /// <summary>
        ///
        /// </summary>
        [StringLength(50)]
        public String BankArea {set;get;}
        /// <summary>
        ///
        /// </summary>
        public Nullable<Int32> SalaryGroup {set;get;}
        /// <summary>
        ///
        /// </summary>
        public DateTime JoinDate {set;get;}
        /// <summary>
        ///
        /// </summary>
        public Nullable<DateTime> QuitDate {set;get;}
        /// <summary>
        ///
        /// </summary>
        public Int32 IsLeader {set;get;}
        /// <summary>
        ///
        /// </summary>
        public Decimal PaidHoliday {set;get;}
        /// <summary>
        ///
        /// </summary>
        public Int32 Status {set;get;}
        /// <summary>
        ///
        /// </summary>
        public Int32 StatusJob {set;get;}
        /// <summary>
        ///
        /// </summary>
        [StringLength(50)]
        public String OriginalId {set;get;}
        /// <summary>
        ///
        /// </summary>
        public Nullable<Guid> LastUpdateUser {set;get;}
        /// <summary>
        ///
        /// </summary>
        public Nullable<DateTime> LastUpdateDate {set;get;}
        /// <summary>
        ///
        /// </summary>
        public Nullable<Guid> CreateUser {set;get;}
        /// <summary>
        ///
        /// </summary>
        public Nullable<DateTime> CreateDate {set;get;}
    }

}
// It's the end
