// Code generated by a template
using System;
using System.ComponentModel.DataAnnotations;

namespace EF.T4.Mssql.ZS
{
    public partial class GZ_Function
    {
        /// <summary>
        ///
        /// </summary>
        [Key]
        public Guid Id {set;get;}
        /// <summary>
        ///
        /// </summary>
        [Required]
        [StringLength(50)]
        public String Name {set;get;}
        /// <summary>
        ///
        /// </summary>
        [StringLength(500)]
        public String URL {set;get;}
        /// <summary>
        ///
        /// </summary>
        public Nullable<Guid> ParentId {set;get;}
        /// <summary>
        ///
        /// </summary>
        [StringLength(500)]
        public String Ico {set;get;}
        /// <summary>
        ///
        /// </summary>
        public Int32 Order {set;get;}
        /// <summary>
        ///
        /// </summary>
        public Nullable<Guid> LastUpdateUser {set;get;}
        /// <summary>
        ///
        /// </summary>
        public Nullable<DateTime> LastUpdateDate {set;get;}
        /// <summary>
        ///
        /// </summary>
        public Nullable<Guid> CreateUser {set;get;}
        /// <summary>
        ///
        /// </summary>
        public Nullable<DateTime> CreateDate {set;get;}
    }

}
// It's the end
