// Code generated by a template
using System;
using System.ComponentModel.DataAnnotations;

namespace EF.T4.Mssql.ZS
{
    public partial class GZ_MonthlySalaryDetail
    {
        /// <summary>
        ///
        /// </summary>
        [Key]
        public Guid Id {set;get;}
        /// <summary>
        ///
        /// </summary>
        public Guid EmployeeId {set;get;}
        /// <summary>
        ///
        /// </summary>
        public Guid DepartmentId {set;get;}
        /// <summary>
        ///
        /// </summary>
        public Guid FinancailUnitId {set;get;}
        /// <summary>
        ///
        /// </summary>
        [Required]
        [StringLength(200)]
        public String BaseSalary_Pwd {set;get;}
        /// <summary>
        ///
        /// </summary>
        [Required]
        [StringLength(200)]
        public String BonusSalary_Pwd {set;get;}
        /// <summary>
        ///
        /// </summary>
        [Required]
        [StringLength(200)]
        public String TotalSalary_Pwd {set;get;}
        /// <summary>
        ///
        /// </summary>
        public Decimal SalaryDays {set;get;}
        /// <summary>
        ///
        /// </summary>
        [Required]
        [StringLength(200)]
        public String PayableSalary_Pwd {set;get;}
        /// <summary>
        ///
        /// </summary>
        [Required]
        [StringLength(200)]
        public String AwardMoney_Pwd {set;get;}
        /// <summary>
        ///
        /// </summary>
        [Required]
        [StringLength(200)]
        public String PercentageMoney_Pwd {set;get;}
        /// <summary>
        ///
        /// </summary>
        [Required]
        [StringLength(200)]
        public String MakeupMoney_Pwd {set;get;}
        /// <summary>
        ///
        /// </summary>
        [Required]
        [StringLength(200)]
        public String PayableOther_Pwd {set;get;}
        /// <summary>
        ///
        /// </summary>
        [Required]
        [StringLength(200)]
        public String SocialMoney_Pwd {set;get;}
        /// <summary>
        ///
        /// </summary>
        [Required]
        [StringLength(200)]
        public String HouseMoney_Pwd {set;get;}
        /// <summary>
        ///
        /// </summary>
        [Required]
        [StringLength(200)]
        public String PunishMoney_Pwd {set;get;}
        /// <summary>
        ///
        /// </summary>
        [Required]
        [StringLength(200)]
        public String CreditMoney_Pwd {set;get;}
        /// <summary>
        ///
        /// </summary>
        [Required]
        [StringLength(200)]
        public String ReduceOther_Pwd {set;get;}
        /// <summary>
        ///
        /// </summary>
        public Guid SubjectId {set;get;}
        /// <summary>
        ///
        /// </summary>
        public Guid CompanyId {set;get;}
    }

}
// It's the end
